apiVersion: v1
kind: pod
metadata:
  name: vol-pod
  env: non-prod


spec:
  containers:
    - name: nginx-vol-pod
      image: nginx
      ports:
        containerPort: 80
      volumeMounts:
      - mountPath: "/nginx/data/nginx.html"
        name: inginx-aws-volume   

  Volumes:
    - name: inginx-aws-volume
      awsElasticBlockStore:
        volumeID: "<volume-id>"
        fstype: txt4
          